### ISSUE TITLE
Implementazioni da fare (caso d'uso: prenotazione appuntamento)

### ISSUE THREAD

**Issue by SystemDss** [MicheleIessi/appointment-manager#6]
- Il cliente non può avere più di un appuntamento lo stesso giorno.
- Il cliente non può avere più di tre appuntamenti (futuri) sull'agenda di un dato professionista.
- Il cliente non deve poter prenotarsi per orari passati.
- Se il cliente ha necessità di cancellare un appuntamento deve farlo al massimo due giorni prima della data di avvenimento dello stesso. In questo caso il sistema deve mandare una mail al professionista per notificare l'annullamento.
- Il professionista deve poter cancellare appuntamenti. In questo caso il sistema deve mandare una mail al cliente per notificare l'annullamento. (Suggerimento: forse si dovrebbe anche in questo caso implementare un limite di tempo)

**Comment by MicheleIessi** [comment]
Aggiunto in [https://github.com/MicheleIessi/appointment-manager/commit/141f422cb8ec868e40102bc0099b9f2795371c0b](https://github.com/MicheleIessi/appointment-manager/commit/141f422cb8ec868e40102bc0099b9f2795371c0b)
